//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Paniers = new HashSet<Paniers>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string email { get; set; }
        public string passwd { private get; set; }
        public string adr_ligne1 { get; set; }
        public string adr_ligne2 { get; set; }
        public string adr_cp { get; set; }
        public string adr_ville { get; set; }
        public Nullable<System.DateTime> archive { get; set; }
        public string statut { private get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paniers> Paniers { get; set; }
    }
}
