//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paniers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paniers()
        {
            this.PanierLignes = new HashSet<PanierLignes>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual Clients Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanierLignes> PanierLignes { get; set; }
    }
}
